### ISSUE TITLE
Request: support item origin url

### ISSUE THREAD

**Issue by GeorgeHahn** [jlnostr/wallabag-api#7]
The origin url property stores the original url for urls that are changed by wallabag. My specific use case is to retrieve youtube urls (wallabag changes these to point to oembed xml documents).

API added in: https://github.com/wallabag/wallabag/pull/3553

**Comment by jlnostr** [comment]
Hi George,
thanks for submitting the issue. Unfortunately, I'm not actively developing the API anymore. 

PRs are still welcome though. From looking at the source code from my smartphone, I think the property just needs to be added to the [`WallabagItem` class](https://github.com/jlnostr/wallabag-api/blob/master/wallabag.Api/Models/WallabagItem.cs), that should do the trick.
